image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: false

install:

  - java -jar ./artifacts/app-mbank.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации